Fixes with roles and access to project settings. Added tooltips to users initials
RTUITLab/ITLab-Projects-Front pull request #36
Opened 2021-11-13 18:12 UTC by FineBot

2021-11-13 18:52 UTC, CAPCHIK requested changes
Не проверял стили, не вникал в структуру
Странно выглядит куча проверок на isEdit, это в целом из-за того, что на одной странице контент сильно витиеватый, но просто выглядит опасно для новых изменений

С названием PR уже лучше, теперь есть претензия к названию ветки источника, аналогично должны работать так, чтобы ветка отражала функционал, который в ней делаешь, и под неё PR

Есть задача - завел ветку, кинул PR

Есть еще одна - от master заводишь еще одну, кидаешь PR

Так, чтобы для ревью и проверки изменения были отдельные, это и заставит писать код лучший, для того чтобы в таких ситуациях не плодились конфликты

2021-11-13 18:52 UTC, CAPCHIK commented on src/checkPermissions.js
> +  const identity = process.env.REACT_APP_ITLAB_IDENTITY || "https://identity.manage.rtuitlab.dev"
Нельзя в коде указывать ссылки на конкретный прод. Дефолтное значение должно ссылать на localhost
Как возможное - указывай `http://127.0.0.1.xip.io:5501` ибо на нем поднимается тестовый identity

2021-11-13 18:52 UTC, CAPCHIK commented on src/components/ProjectCard/ProjectCard.js
> +                  <Tooltip
Весь этот компонент используется много раз, логичнее вынести его отдельно, и вызывать с параметром "информация о пользователе", чем копипастить везде одно и тоже, с магинческим нулевым индексом, и прочим

2021-11-13 18:52 UTC, CAPCHIK commented on src/components/ProjectCard/ProjectCard.js
> +                        key={i}
Не понимаю для чего тут нужен key, помнится он нужен при итерациях, но тут её нет, а если и он итерируется в родительском компоненте - то key все равно нужен только в корневом элементе итерации

2021-11-13 18:52 UTC, CAPCHIK commented on src/components/RectangleLable/RectangleLable.js
>  export default function RectangleLable(props) {
Что за название компонента `RectangleLable`? Лично мне не ясно, что это и зачем, не говоря о граматике

Либо переименовать надо, либо добавить JSDoc

2021-11-13 18:52 UTC, CAPCHIK commented on src/components/RightButtonsBlock/RightButtonsBlock.js
>  export default function RightButtonsBlock(props) {
Аналогично c `RectangleLable` что за кнопки справа? На проекте с несколькими кнопками справа - это не говорящее название, либо корректировать название, либо выносить в подпапку, для контекста, о каком "право" говорим, либо JSDoc

2021-11-13 18:52 UTC, CAPCHIK commented on src/pages/ProjectEdit.js
> +                            <Tooltip
Снова повторяющийся компонент аватара

2021-11-13 18:52 UTC, CAPCHIK commented on src/pages/ProjectSettings.js
> +                <Tooltip text={ownerData[0]?.lastName + " " + ownerData[0]?.firstName + " " + ownerData[0]?.middleName}
И снова повторение

2021-11-13 18:52 UTC, CAPCHIK commented on src/pages/ProjectSettings.js
> +                            <Tooltip
И опять

2021-11-13 18:52 UTC, CAPCHIK commented on src/pages/ProjectSettings.js
> +  if (state.projectInfo === null || state.projectInfo === undefined) {
Зачем делать проверку на null и undefined если можно написать `if (!state.projectInfo)`? Возможно я не в курсе, но мне кажется любое falseable значение подойдет

2021-11-13 18:52 UTC, CAPCHIK commented on src/pages/VersionSettings.js
> +  const canEdit = state.isOwner===true || state.isOwner==="version"
Нужен комментарий от @IvLaptev насколько это удобно и правильно хранить в значении или bool или string, при том что используется JS, а не TS, и соответственно нигде нет описания по типу `type OwnerFlag = bool || "version"`, или подобного, не помню наизусть как множество типов в TS совмещаются

2021-11-13 18:53 UTC, CAPCHIK commented
> На последний кейс просто нужен второй аккаунт, а я сижу либо через админа, либо через Фоменкова, но у него нет доступа к проектам на деве

На dev нужен доп аккаунт для тестирования? @Suput  сделай, думаю, несколько аккаунтов и закрепи их в канале `itlab` чтобы все могли ими пользоваться, с описанием, у кого какие claim присутствуют

2021-11-13 21:39 UTC, IvLaptev commented on src/pages/VersionSettings.js
> +  const canEdit = state.isOwner===true || state.isOwner==="version"
Комментирую. Вне зависимости от того, используется JS или TS, не стоит заниматься хранением в одной переменной различных типов данных.

2021-11-13 21:57 UTC, IvLaptev commented on src/components/ProjectCard/ProjectCard.js
> +                        key={i}
А здесь я с тобой не соглашусь на счёт key. Тут из-за дифа обрезается `map()`, который сильно выше.
https://github.com/RTUITLab/ITLab-Projects-Front/blob/71306c15b6074fc56d0242c8279c670e30e73096/src/components/ProjectCard/ProjectCard.js#L169

Скорее вопрос должен быть в том, почему он не на тултипе, а на юзер аватаре. И ещё, не стоит в виде ключа использовать индекс, это плохо и лучше заменить на какоё-то уникальный для элемента id или ещё что-то. зависящее только от элемента.

2021-11-13 22:56 UTC, IvLaptev requested changes
В `src/checkPermissions.js` очень странно выглядят проверки на `null` и `undefined`, написанные через равенство/неравенство. А дальше по списку.

2021-11-13 22:56 UTC, IvLaptev commented on src/components/UserAvatar/UserAvatar.js
> +        nClick={(e)=>{
Если этот код относится к обработке событий, то я сомневаюсь, что он отработает

2021-11-13 22:56 UTC, IvLaptev commented on src/components/UserAvatar/UserAvatar.js
> +      }} inProject={inProject?("yes"):("no")} className={styles.userAvatar} style={{backgroundColor:colors[props.i%colors.length],display:"flex",alignItems:"center", justifyContent:"center"}}>
Стили, которые не зависят ни от чего, стоит положить в класс, раз уж он есть (половина из них там и так есть).

2021-11-13 22:56 UTC, IvLaptev commented on src/components/UserAvatar/UserAvatar.js
> +      }} inProject={inProject?("yes"):("no")} className={styles.userAvatar} style={{backgroundColor:colors[props.i%colors.length],display:"flex",alignItems:"center", justifyContent:"center"}}>
То же самое касается и [этого](https://github.com/RTUITLab/ITLab-Projects-Front/blob/71306c15b6074fc56d0242c8279c670e30e73096/src/components/UserAvatar/UserAvatar.js#L29-L30)

2021-11-13 22:56 UTC, IvLaptev commented on src/pages/ProjectSettings.js
> +    window.onscroll = null
Данная строчка вмешивается в поведение сайта, за которое отвечает совершенно другой микрофронтенд. Для того чтобы это использовать, должна быть ну очень веская причина. Требуется пояснение.

2021-11-13 22:56 UTC, IvLaptev commented on src/pages/ProjectSettings.js
> +    setTimeout(() => setTab(1), 50)
Зачем этот костыль?

2021-11-13 22:56 UTC, IvLaptev commented on src/pages/VersionSettings.js
>    let id = window.location.toString().match(/versions\/([^\/#?]*)\/*/)[1]
Я совершенно не уверен, что это уместно здесь. Для таких вещей существует отдельный хук в реакте.

2021-11-13 22:56 UTC, IvLaptev commented on src/pages/VersionSettings.js
> +                              src={edit} style={{ marginLeft: "5px", cursor: "pointer", width: "19px", height: "19px" }}
Эти `19px` раскиданы по всему файлу и встречаются не менее пяти раз. Это надо в отдельный стиль вынести.

2021-11-13 22:56 UTC, IvLaptev commented on src/pages/VersionSettings.js
> +                        type={state.currentUserId.toString()===e.author.toString() || canEdit ?"edit":""}
Чем обусловлено приведение строк к строкам? Требуется пояснение.

2021-11-13 22:56 UTC, IvLaptev commented on src/checkPermissions.js
> +
Не понимаю, зачем `if`, внутри которого ничего нет. Если внутри хоть что-то появится, то надо хотя бы TODO всунуть внутрь, в противном случае менять условие на противоположенное и выполнять то, что в `else`.

2021-11-14 08:24 UTC, CAPCHIK commented on src/components/ProjectCard/ProjectCard.js
> +                        key={i}
Вот о том и речь, да, что он должен быть на корневом компоненте, видно когда оборачивал в тултип - забыл про это

2021-11-16 08:56 UTC, CAPCHIK approved these changes
Сейчас изменения выглядят уже более опрятными, все комментарии носят рекомендательный характер на будущее

2021-11-16 08:56 UTC, CAPCHIK commented on src/checkPermissions.js
> +    for(let i of jwt.itlab){
В рамках рекомендации - в JS есть общепринятый и распространенный метод для поиска элементов - метод `some`, который на стрелочную функцию вернет bool, есть такой элемент или нет.

2021-11-16 08:56 UTC, CAPCHIK commented on src/checkPermissions.js
> +function parseJwt (token) {
Тут вопрос к @IvLaptev информация, которая кладется в токен, также отдается при логине, или при прогулке по user endpoint в identity server
Не лучше ли такую информацию пихать в фронтенды единым образом? Чтобы информация о пользователе была в людях через механизм single-spa?

2021-11-16 08:56 UTC, CAPCHIK commented on src/components/Input/Input.js
>  export default function Input(props) {
Идея в том, чтобы использовать один компонент Input для введения всех мыслимых и немыслимых данных?

2021-11-16 08:56 UTC, CAPCHIK commented on src/components/ProjectCard/ProjectCard.js
> +        <UsersList contributors={props.contributors} limit={4} parentStyle={"none"}/>
Огонь! Буду рад бОльшему количеству подобных решений!

2021-11-16 08:56 UTC, CAPCHIK commented on src/components/ProjectEditNavbar/ProjectEditNavbar.js
> +      {state.role==="owner"?(<Link to={"/projects/edit/" + props.id}>
Снова как рекомендация - так как state формируется собственноручно - можно в нем сделать специальный метод isOwner(), внутри которого будет проверка с константной строкой
Идея в том, что завязываться на константы опасно, это раз. И не выносить их в глобальное место, а просто писать в коде это еще хуже, это два
В данном случае все не так опасно, ведь `owner` это строка, которую формирует и проверяет сам front, но тем не менее с точки зрения грамотности кода это не лучшее решение, ведь всем нужно знать, что именно эта строка используется, и чем помнить об этом - лучше заглянуть в список существующих методов

2021-11-16 08:56 UTC, CAPCHIK commented on src/pages/ProjectSettings.js
> +            {state.role!=="user" ? <Button type={"black"}>Управление</Button> : null}
Аналогично с комментарием выше - лучше вынести как методы, если часто нужен метод - лучше написать метод по типу `moreThanUser()`, ибо не равен пользователю по семантике кода может означать, что роли нет вовсе, что не совсем правда, и тут разработчик должен сам догадаться, что если не пользователь, это наверно или админ версии, или проекта, или суперюзер
А метод `isMoreThanUser()` сразу объясняет, что происходит
Про название метода не знаю, можно спросить @IvLaptev

2021-11-16 08:56 UTC, CAPCHIK commented on src/pages/ProjectsList.js
> +  function sc(){
Комментарий — это отлично, но `sc`? Серьезно?) 
Хотя, судя по комментариям ниже - весь код с прокруткой планируется переписывать, так что пока окей

2021-11-16 08:56 UTC, CAPCHIK commented on src/pages/VersionSettings.js
> +  const canEdit = state.role==="owner" || state.role==="version"
Аналогично к комментарию выше - можно написать метод по типу `canEditVersion`, в котором будет нужная проверка, и не будет хардкода

2021-11-16 12:01 UTC, IvLaptev commented on src/checkPermissions.js
> +function parseJwt (token) {
Эта информация передаётся фронтендам

https://github.com/RTUITLab/ITLab-Projects-Front/blob/7b13507e66119fd00ca2a18d1e68172d98565b08/src/App.js#L70-L78

2021-11-16 13:41 UTC, IvLaptev commented
@FineBot, я не совсем понял в компоненте Input, зачем потребовалось что то класть в `e.target.value` напрямую через DOM, если в реакте это всё-таки стоит делать через state и аттрибута `value` в инпуте. Сможешь пояснить?

2021-11-17 15:04 UTC, IvLaptev approved these changes

2021-11-17 15:06 UTC, CAPCHIK commented
@Suput Ждем ждем ждем)

2021-11-17 15:18 UTC, merged