Tooltips
RTUITLab/ITLab-Projects-Front pull request #55
Opened 2022-02-02 09:58 UTC by baikinkirill

Изменена логика определения позиции тултипов. Теперь она задается только при появлении тултипа. Есть три позиции: слева, справа и по середине, которые заданы в css. Это нужно, чтобы на мобилках или других узких экранах не было горизонтального скролла.

2022-02-02 09:59 UTC, Suput commented
@baikinkirill Оно есть на деве, чтобы можно было протестировать?

2022-02-02 10:00 UTC, baikinkirill commented
> @baikinkirill Оно есть на деве, чтобы можно было протестировать?

Да

2022-02-02 11:03 UTC, Suput commented
Получается Tooltip всегда вправо смотрят?

2022-02-02 12:31 UTC, baikinkirill commented
> Получается Tooltip всегда вправо смотрят?

Нет, по умолчанию они находятся слева от элемента. Если слева места не хватает, то справа, но если и справа тоже не хватает, то тултип уменьшается и становится посередине

2022-02-03 17:21 UTC, IvLaptev requested changes
Полагаю, что встретил я всего 2 алерта из огромного количества. Изменить надо не только те 2, на которые я указал, но и все, что есть в проектах.

2022-02-03 17:21 UTC, IvLaptev commented on src/components/popouts/EditDeadline.js
> +  const checkYear = (str) => {
Не совсем понял, зачем здесь самостоятельно парсить строки, если год можно взять из Date

2022-02-03 17:21 UTC, IvLaptev commented on src/components/popouts/Popout.module.scss
> +    //background: rgba(0, 0, 0, 0.05);
Зачем стоит комментарий?
Если это где-то будет ещё использоваться надо написать об этом в том же комментарии, а если нет, то просто удалить строку.

2022-02-03 17:21 UTC, IvLaptev commented on src/pages/ProjectsList.js
> +      switch (lastTabId) {
Если уж используешь switch-case, то указывай хотя бы, что значит каждый конкретный case. Потому что сходу понять совершенно невозможно.

2022-02-03 19:22 UTC, baikinkirill commented on src/components/popouts/EditDeadline.js
> +  const checkYear = (str) => {
Нужен год с четырьмя цифрами

2022-02-04 06:09 UTC, IvLaptev requested changes

2022-02-04 06:09 UTC, IvLaptev commented on src/components/popouts/EditAvatarCard.js
> +          <img src={state.theme === "dark" ? (closeDark) : (close)} alt="" />
Повышаем accessibility. Где есть `img`, там должен быть указан **адекватный** `alt`

2022-02-04 06:09 UTC, IvLaptev commented on src/components/popouts/EditDeadline.js
> +  const checkYear = (str) => {
А что тогда даёт getFullYear()?

2022-02-04 11:18 UTC, baikinkirill commented
> Зачем нужны эти проверки, если ты только что проверил?
> 
> ```js
> if(!e.lastName && !e.firstName && !e.middleName){
>   e.lastName="Без имени"
>   e.firstName=""
>   e.middleName=""
> }
> ```

Если аккаунту полностью ничего не задано - задаем "Без имени"
иначе делаем пустые поля, чтобы не было undefined

2022-02-04 11:21 UTC, baikinkirill commented
> @IvLaptev увидел краем глаза что в catch обрабатывается test версия для подкладки тестовых данных. В моём миропонимании сам сервис с данными должен отдавать сразу моковые значения, а в самом компоненте надеяться только на верный поток, и не думать, что его могут обмануть
> 
> Не считаю, что это нужно срочно править прямо сейчас, но запомнить про такую фишку, и провести рефакторинг было бы полезно

если на проде вылезет ошибка, то он вернет ето:
![image](https://user-images.githubusercontent.com/10910903/152520572-3c39aea9-e7c4-4d08-b2ab-2ef78ae5eb91.png)

2022-02-04 13:24 UTC, CAPCHIK commented
> > @IvLaptev увидел краем глаза что в catch обрабатывается test версия для подкладки тестовых данных. В моём миропонимании сам сервис с данными должен отдавать сразу моковые значения, а в самом компоненте надеяться только на верный поток, и не думать, что его могут обмануть
> > Не считаю, что это нужно срочно править прямо сейчас, но запомнить про такую фишку, и провести рефакторинг было бы полезно
> 
> если на проде вылезет ошибка, то он вернет ето: ![image](https://user-images.githubusercontent.com/10910903/152520572-3c39aea9-e7c4-4d08-b2ab-2ef78ae5eb91.png)

Это то понятно, просто то, что компонент сам себе создает данные - это странно
Есть отдельный сервис, который в зависимости от того, в тесте он или нет - должен давать соответствующие данные. В то время как компонент должен просто красиво их отрисовывать.

Я понимаю, что на проде все ок, тут я говорю не про публичный функционал, а про структуру кода

2022-02-04 13:53 UTC, IvLaptev requested changes

2022-02-04 13:53 UTC, IvLaptev commented on src/App.js
>        // HappyBirthday()
Сомневаюсь в том, что данный комментарий здесь нужен

2022-02-04 13:53 UTC, IvLaptev commented on src/components/TasksTable/TasksTable.js
>    function preventDefault(e) {
Данная функция нигде не используется, после удаления кусок кода

2022-02-04 13:53 UTC, IvLaptev commented on src/components/TasksTable/TasksTable.js
>                        <React.Fragment key={md5(JSON.stringify(workerElement))}>
Всё ещё хэш

2022-02-04 13:53 UTC, IvLaptev commented on src/components/Tooltip/Tooltip.js
> +  const [elemAttr, setElemAttr] = useState(props?.defaultPosition?props.defaultPosition:"left")
Просьба поставить пробелы в тернарном операторе, потому что вообще не понятно некоторое время, что тут написано

2022-02-04 13:53 UTC, IvLaptev commented on src/components/popouts/CreateNewVersionTask.js
>                let buffe = JSON.parse(JSON.stringify(state.currentVersion))
Для чего здесь полное копирование объекта?

2022-02-04 13:53 UTC, IvLaptev commented on src/components/popouts/CreateNewVersionTask.js
>                let buffe = JSON.parse(JSON.stringify(state.currentVersion))
И [тут](https://github.com/RTUITLab/ITLab-Projects-Front/pull/55/files#diff-bd6ef02f02dbc6ec78a01a5640738425d96485fbb49f4e6723cd222c7e602a8eR82) тоже

2022-02-04 20:01 UTC, IvLaptev approved these changes

2022-02-04 20:26 UTC, merged