Build via docker
RTUITLab/ITLab-Projects-Front pull request #65
Opened 2022-02-15 20:10 UTC by Suput

Странное примечание: у меня локально образ не собирается, у другого коллеги собирается. На азуре образ тоже собирается. Ах да, если руками (не через Докер), то собирается

2022-02-16 06:18 UTC, CAPCHIK requested changes

2022-02-16 06:18 UTC, CAPCHIK commented on azure-pipelines.yml
> +  - stage: pushDockerImage
Аналогично с https://github.com/RTUITLab/ITLab-Reports-Front/pull/46 не сработает сборка в одной стадии и пуш в другой, это разные машины

2022-02-16 10:16 UTC, CAPCHIK approved these changes

2022-02-16 10:16 UTC, CAPCHIK commented on azure-pipelines.yml
> +    condition: ${{ variables.buildImage }}
По идее это условие уже не нужно, ибо просто сборка - это нормально для всех веток

2022-02-16 10:38 UTC, CAPCHIK approved these changes

2022-02-18 11:11 UTC, Suput reviewed
Изменить логику с коммитом

2022-02-18 11:11 UTC, Suput commented on src/pages/ProjectsList.js
> +                      window.open("https://github.com/RTUITLab/ITLab-Projects-Front/commit/" + process.env.REACT_APP_SOURCE_COMMIT_HASH)
@baikinkirill мы с тобой обсуждали, что ссылку на репозиторий я тебе тоже даю. Вот для кого [эта](https://github.com/RTUITLab/ITLab-Projects-Front/blob/bb08eba594de4ad902397776ba33d225ea5dec4b/.env.build-info#L2) переменная?
Во-первых, сделай так: `process.env.REACT_APP_SOURCE_REMOTE_URL + "/commit/" + process.env.REACT_APP_SOURCE_COMMIT_HASH`
Во-вторых, ты же сам хотел сделать по красоте и показывать ещё и ветку? Я тебе опять же завёл [переменную](https://github.com/RTUITLab/ITLab-Projects-Front/blob/bb08eba594de4ad902397776ba33d225ea5dec4b/.env.build-info#L1)
И мы обсуждали логику такую:
> Код ниже написан на псевдоязыке
```
if (proccess.env.REACT_APP_SOURCE_BRANCH.startswith("refs/heads")) {
    print "Ветка " proccess.env.REACT_APP_SOURCE_BRANCH.split("/")[2]
} else if (proccess.env.REACT_APP_SOURCE_BRANCH.startswith("refs/tags")) {
    print "Тэг " proccess.env.REACT_APP_SOURCE_BRANCH.split("/")[2]
}
```

2022-02-23 08:30 UTC, Suput reviewed
Проверил ссылки - всё работает

2022-02-23 20:49 UTC, CAPCHIK approved these changes

2022-02-25 19:18 UTC, IvLaptev approved these changes

2022-02-25 19:21 UTC, merged